# -*- coding: utf-8 -*-
"""Transfo Odoo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZPfDEoSrSmUx_vrQeghHiA8QT7OEdln
"""

import pandas as pd
import numpy as np
import unicodedata
from pathlib import Path


# =========================
# OUTILS GÉNÉRAUX
# =========================

def normalize_text(value):
    if pd.isna(value):
        return ""
    value = str(value).strip()
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    value = value.upper()
    value = " ".join(value.split())
    return value


def to_str(value):
    if pd.isna(value):
        return ""
    return str(value).strip()


def safe_round(value, decimals=3):
    if pd.isna(value) or value == "":
        return np.nan
    try:
        return round(float(value), decimals)
    except Exception:
        return np.nan


def format_number_fr(value, decimals=3):
    if pd.isna(value) or value == "":
        return ""
    try:
        value = round(float(value), decimals)
        txt = f"{value:.{decimals}f}"
        txt = txt.rstrip("0").rstrip(".")
        return txt.replace(".", ",")
    except Exception:
        return to_str(value)


def format_percent_no_decimal(value):
    if pd.isna(value) or value == "":
        return ""
    try:
        return str(int(round(float(value) * 100)))
    except Exception:
        return ""


# =========================
# RÉFÉRENTIEL
# =========================

ALIASES_02 = {
    "CONQUETE": "CONQUETE (AUTRES)",
    "CONQUÊTE": "CONQUETE (AUTRES)",
    "RENOUVELLEMENT": "RENOUVELLEMENT",
    "VENTE ADDITIONNELLE": "VENTE ADDITIONNELLE",
}

ALIASES_03 = {
    "ELECTRICITE": "ELECTRICITE",
    "ÉLECTRICITÉ": "ELECTRICITE",
    "GAZ": "GAZ",
}

ALIASES_04 = {
    "ENERGY PRO CONSULTING": "ENERGY PRO",
    "CABINET BRUERE ENERGIES": "CABINET BRUERE ENERGIES (CBE)",
    "REZO ENERGY": "REZO ENERGY - NES SALES",
    "STEPHANIE MIROUX": "STEPHANIE MIROUX",
    "STÉPHANIE MIROUX": "STEPHANIE MIROUX",
    "NOLWENN FAVRE": "NOLWENN FAVRE",
    "BENOIT VILCOT": "BENOIT VILCOT",
    "BENOIT VILCOT ": "BENOIT VILCOT",
    "MYLENE PROST": "MYLENE PROST",
    "MYLÈNE PROST": "MYLENE PROST",
    "PIERRE-JEAN HAURE": "PIERRE-JEAN HAURE",
    "ENOPTEA": "ENOPTEA",
    "VS ENERGIE": "VS ENERGIE",
    "D.A. CONSULTING": "D.A.. CONSULTING",
}


def load_referentiel(referentiel_path):
    ref = pd.read_excel(referentiel_path, sheet_name=0, dtype=object)
    ref.columns = [str(c).strip() for c in ref.columns]

    required_cols = {"Plan", "Compte analytique", "ID"}
    missing = required_cols - set(ref.columns)
    if missing:
        raise ValueError(f"Colonnes manquantes dans le référentiel : {missing}")

    ref["Plan_norm"] = ref["Plan"].apply(normalize_text)
    ref["Compte_norm"] = ref["Compte analytique"].apply(normalize_text)
    ref["ID"] = ref["ID"].astype(str).str.strip()

    maps = {}
    for plan_name in ref["Plan_norm"].dropna().unique():
        subset = ref[ref["Plan_norm"] == plan_name].copy()
        maps[plan_name] = dict(zip(subset["Compte_norm"], subset["ID"]))

    return maps, ref


def get_ref_id(maps, plan, label, default=None, aliases=None):
    plan_norm = normalize_text(plan)
    label_norm = normalize_text(label)

    if aliases and label_norm in aliases:
        label_norm = normalize_text(aliases[label_norm])

    return maps.get(plan_norm, {}).get(label_norm, default)


def build_codes_from_referentiel(df, maps):
    # BU
    bu_externe = get_ref_id(maps, "01 - BU", "01- Courtage Externe", default="49")
    bu_interne = get_ref_id(maps, "01 - BU", "02 - Courtage Internes", default="48")

    df["Gestionnaire-BU"] = np.where(
        df["Apporteur d'affaire"].fillna("").astype(str).str.strip().str.upper() != "CAPITOLE ENERGIE",
        "{" + str(bu_externe),
        "{" + str(bu_interne)
    )

    # Type
    df["Type"] = df["Type"].apply(
        lambda x: get_ref_id(maps, "02 - Niveau", x, default=None, aliases=ALIASES_02)
    )

    # Produit
    df["Valeur:Produit"] = df["Lignes de la commande/Produit"].apply(
        lambda x: get_ref_id(maps, "03 - Niveau", x, default=None, aliases=ALIASES_03)
    )

    # Codes apporteur / vendeur
    def map_codes_ok(row):
        apporteur = row.get("Apporteur d'affaire", "")
        vendeur = row.get("Vendeur", "")

        code_apporteur = get_ref_id(maps, "04 - Niveau", apporteur, default=None, aliases=ALIASES_04)
        if code_apporteur is not None:
            return str(code_apporteur)

        code_vendeur = get_ref_id(maps, "04 - Niveau", vendeur, default=None, aliases=ALIASES_04)
        if code_vendeur is not None:
            return str(code_vendeur)

        return "0"

    df["Codes OK"] = df.apply(map_codes_ok, axis=1)

    # Capitole Energie AA
    ce_aa = get_ref_id(maps, "04 - Niveau", "Capitole Energie AA", default="76", aliases=ALIASES_04)
    df["Capitole Energie AA"] = np.where(
        df["Gestionnaire-BU"].astype(str).str.startswith("{49"),
        str(ce_aa),
        None
    )

    return df


# =========================
# TRANSFORMATION PRINCIPALE
# =========================

def transform_import_odoo(input_excel_path, referentiel_path, output_excel_path=None, sheet_name="Import Odoo"):
    input_excel_path = Path(input_excel_path)
    referentiel_path = Path(referentiel_path)

    if output_excel_path is None:
        output_excel_path = input_excel_path.with_name(f"{input_excel_path.stem}_transforme.xlsx")
    else:
        output_excel_path = Path(output_excel_path)

    # Lecture brute de l'onglet Import Odoo
    df = pd.read_excel(input_excel_path, sheet_name=sheet_name, header=None, dtype=object)

    # Reproduction du comportement Power Query :
    # Table.AlternateRows(..., 0, 15, 30000) => on garde à partir de la ligne 16
    df = df.iloc[15:].copy().reset_index(drop=True)

    # Noms temporaires Column1...
    df.columns = [f"Column{i}" for i in range(1, len(df.columns) + 1)]

    # Column17 -> Type avant promotion d'entêtes
    if "Column17" in df.columns:
        df = df.rename(columns={"Column17": "Type"})

    # Promotion des en-têtes
    headers = df.iloc[0].tolist()
    df = df.iloc[1:].copy().reset_index(drop=True)
    df.columns = headers

    # Suppression colonnes inutiles
    if "Column1" in df.columns:
        df = df.drop(columns=["Column1"])
    if "Column4" in df.columns:
        df = df.drop(columns=["Column4"])

    # Renommage colonnes
    rename_map = {
        "Fournisseur  ↑": "Client",
        "Date de Début Souhaitée": "Lignes de la commande/Description3",
        "Date de fin contrat CE": "Lignes de la commande/Description4",
        "Account Name": "Lignes de la commande/Description1",
        "Compteur": "Lignes de la commande/Description2",
        "Durée": "Lignes de la commande/Description5",
        "CAR validée fournisseur (MWh)": "Lignes de la commande/Description6",
        "Propriétaire de l'opportunité": "Vendeur",
        "Energie": "Lignes de la commande/Produit",
        "Pourcentage rétrocession": "Pourcentage.1",
        "Gestionnaire": "Apporteur d'affaire",
        "Prévisionnel commision": "Lignes de la commande/Prix Unitaire",
        "Date de signature": "Lignes de la commande/Date de signature",
        "Column19": "Lignes de la commande/Distribution Analytique",
    }
    df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})

    # Chargement référentiel
    maps, ref_df = load_referentiel(referentiel_path)

    # Construction des champs descriptifs
    if "Lignes de la commande/Description2" in df.columns:
        df = df.rename(columns={"Lignes de la commande/Description2": "PDL"})
        df["Lignes de la commande/Description2"] = "PDL : " + df["PDL"].fillna("").astype(str).str.strip()
        df = df.drop(columns=["PDL"])

    if "Lignes de la commande/Date de signature" in df.columns:
        df["Lignes de la commande/Description"] = (
            "Date de signature : " + df["Lignes de la commande/Date de signature"].fillna("").astype(str).str.strip()
        )

    if "Lignes de la commande/Description1" in df.columns:
        df["Lignes de la commande/Description1"] = (
            "RAISON SOCIALE : " + df["Lignes de la commande/Description1"].fillna("").astype(str).str.strip()
        )

    if "Lignes de la commande/Description5" in df.columns:
        df["Lignes de la commande/Description5"] = (
            "Durée du contrat (en mois) : "
            + df["Lignes de la commande/Description5"].fillna("").astype(str).str.strip()
        )

    if "Lignes de la commande/Description6" in df.columns:
        df["Lignes de la commande/Description6_num"] = df["Lignes de la commande/Description6"].apply(safe_round)
        df["Lignes de la commande/Description6"] = (
            "Consommation annuelle de référence (CAR) : "
            + df["Lignes de la commande/Description6_num"].apply(lambda x: format_number_fr(x, 3))
            + " MWh/an"
        )

    if "Lignes de la commande/Description3" in df.columns:
        df["Lignes de la commande/Description3"] = (
            "Date de début contrat : " + df["Lignes de la commande/Description3"].fillna("").astype(str).str.strip()
        )

    if "Lignes de la commande/Description4" in df.columns:
        df["Lignes de la commande/Description4"] = (
            "Date de fin de contrat : " + df["Lignes de la commande/Description4"].fillna("").astype(str).str.strip()
        )

    # Mapping via référentiel
    df = build_codes_from_referentiel(df, maps)

    # Suppression des 4 dernières lignes comme dans Power Query
    if len(df) >= 4:
        df = df.iloc[:-4].copy()

    # Pourcentage
    df["Pourcentage.1"] = pd.to_numeric(df["Pourcentage.1"], errors="coerce")
    df["Pourcentage"] = df["Pourcentage.1"].apply(format_percent_no_decimal)
    df["Pourcentage Diff AA"] = (100 - (df["Pourcentage.1"] * 100)).round(0)
    df["Pourcentage Diff AA"] = df["Pourcentage Diff AA"].fillna(0).astype(int).astype(str)

    def build_analytics(row):
      bu = to_str(row["Gestionnaire-BU"]).replace("{", "")  # enlève { existant
      type_ = to_str(row["Type"])
      produit = to_str(row["Valeur:Produit"])
      code = to_str(row["Codes OK"])
      pct = to_str(row["Pourcentage"])

    # première ligne
      bloc1 = f'"{bu},{type_},{produit},{code}":{pct}'

    # deuxième ligne (si Capitole Energie AA)
      ce = to_str(row["Capitole Energie AA"])
      pct_diff = to_str(row["Pourcentage Diff AA"])

      if ce:
        bloc2 = f'"{bu},{type_},{produit},{ce}":{pct_diff}'
        return "{" + bloc1 + ", " + bloc2 + "}"
      else:
        return "{" + bloc1 + "}"

    # Colonnes finales
    df["Lignes de la commande/Distribution Analytique"] = df.apply(build_analytics, axis=1)
    df["Lignes de la commande/Type d'affichage"] = "NOTE"
    df["Lignes de la commande/Quantité"] = "1"
    df["Lignes de la commande/Description1.1"] = (
        "Contrat Energie " + df["Lignes de la commande/Produit"].fillna("").astype(str).str.strip()
    )

    # Nettoyage
    cols_to_drop = [
        "Valeur:Produit",
        "Gestionnaire-BU",
        "Codes OK",
        "Pourcentage",
        "Pourcentage Diff AA",
        "Capitole Energie AA",
        "Lignes de la commande/Distribution Analytique1",
        "Analytics fusion",
        "Analytics OK pour fusion",
        "2me Ligne pour fusion",
        "2me Ligne",
        "Vendeur",
        "Type",
        "Apporteur d'affaire",
        "Pourcentage.1",
        "Montant rétrocession Total",
        "Mois pour facturation  ↑",
        "Lignes de la commande/Date de signature",
        "Lignes de la commande/Description6_num",
    ]
    cols_to_drop = [c for c in cols_to_drop if c in df.columns]
    df = df.drop(columns=cols_to_drop)

    # Ordre final
    final_columns = [
        "Client",
        "Lignes de la commande/Produit",
        "Lignes de la commande/Description1.1",
        "Lignes de la commande/Type d'affichage",
        "Lignes de la commande/Description1",
        "Lignes de la commande/Description2",
        "Lignes de la commande/Description",
        "Lignes de la commande/Description3",
        "Lignes de la commande/Description4",
        "Lignes de la commande/Description5",
        "Lignes de la commande/Description6",
        "Lignes de la commande/Quantité",
        "Lignes de la commande/Prix Unitaire",
        "Lignes de la commande/Distribution Analytique",
    ]
    final_columns_existing = [c for c in final_columns if c in df.columns]
    df_final = df[final_columns_existing].copy()


    # Export
    df_final.to_excel(output_excel_path, index=False)

    return df_final, output_excel_path


# =========================
# EXÉCUTION
# =========================

if __name__ == "__main__":
    # À adapter selon tes fichiers
    fichier_source = "Salesforce.xlsx"
    fichier_referentiel = "Comptes analytiques.xlsx"
    fichier_sortie = "Salesforce_transforme.xlsx"

    df_resultat, chemin_sortie = transform_import_odoo(
        input_excel_path=fichier_source,
        referentiel_path=fichier_referentiel,
        output_excel_path=fichier_sortie,
        sheet_name="Import Odoo"
    )

    print(f"Transformation terminée : {chemin_sortie}")
    print(f"Nombre de lignes générées : {len(df_resultat)}")

df_resultat, fichier_sortie = transform_import_odoo(
    input_excel_path="C:/mon_dossier/Salesforce.xlsx",
    output_excel_path="C:/mon_dossier/Salesforce_transforme.xlsx"
)